### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by ECHOWIKM** [SamsonMXVI/go-wenku-downloader#4]
![image](https://github.com/SamsonMXVI/go-wenku-downloader/assets/122116925/3ec079b4-7607-412a-b30f-b6397eb84b78)

[scraper.log](https://github.com/SamsonMXVI/go-wenku-downloader/files/13194696/scraper.log)

**Comment by ECHOWIKM** [comment]
2023/10/28 14:35:41 base.go:68: download failed 下载小说卷信息失败: &{%!e(string=Get) %!e(string=) %!e(*errors.errorString=&{unsupported protocol scheme ""})}
2023/10/28 14:35:51 grab.go:18: 正在下载 http://img.wenku8.com/image/1/1777/1777s.jpg...
2023/10/28 14:35:51 base.go:68: download failed 下载小说卷信息失败: &{%!e(string=Get) %!e(string=) %!e(*errors.errorString=&{unsupported protocol scheme ""})}
2023/10/28 14:36:52 grab.go:18: 正在下载 http://img.wenku8.com/image/1/1973/1973s.jpg...
2023/10/28 14:36:52 base.go:68: download failed 下载小说卷信息失败: &{%!e(string=Get) %!e(string=) %!e(*errors.errorString=&{unsupported protocol scheme ""})}

**Comment by AosakiReiya** [comment]
修复好了～
