### ISSUE TITLE
因无法登录从而无法使用任何功能

### ISSUE THREAD

**Issue by PantsuMeow** [SamsonMXVI/go-wenku-downloader#5]
[scraper.log](https://github.com/SamsonMXVI/go-wenku-downloader/files/13466041/scraper.log)
`登陆失败 Post "https://www.wenku8.net/login.php?do=submit&jumpurl=http%3A%2F%2Fwww.wenku8.net%2Findex.php": read tcp [2409:8a1a:572:f200:1058:9355:7215:dcf5]:50891->[2606:4700:3034::ac43:be48]:443: wsarecv: An existing connection was forcibly closed by the remote host.
未登录-(查询/热门小说)功能将无法使用
欢迎使用轻小说文库下载器，本工具源码链接如下：https://github.com/SamsonMXVI/go-wenku-downloader
? 你打算做什么 搜索小说
请输入要搜索的作者: 渡航
2023/11/26 14:18:18 base.go:56: Search failed Get "https://www.wenku8.net/modules/article/search.php?page=1&searchkey=%B6%C9%BA%BD&searchtype=author": read tcp [2409:8a1a:572:f200:1058:9355:7215:dcf5]:51284->[2606:4700:3034::ac43:be48]:443: wsarecv: An existing connection was forcibly closed by the remote host.
? 你打算做什么  [Use arrows to move, type to filter]
> 查看(今日更新/热门轻小说/总推荐榜/...)
  搜索小说
  下载小说
  什么也不做`

请求作者的帮助，谢谢！:)

**Comment by PantsuMeow** [comment]
? 你打算做什么 下载小说
支持格式:
        数字ID: 1973
        url格式 1: https://www.wenku8.net/book/2975.htm
        url格式 2: https://www.wenku8.net/modules/article/articleinfo.php?id=14&char=&charset=big5
输入小说ID: 1213
2023/11/26 14:28:47 base.go:68: download failed 获取小说信息失败: &{%!e(string=Get) %!e(string=https://www.wenku8.net/book/1213.htm) %!e(*net.OpError=&{read tcp 0xc00002a330 0xc00002a360 0xc000032200})}

**Comment by AosakiReiya** [comment]
我这边可以使用，试试用ipv4?

**Comment by PantsuMeow** [comment]
登陆失败 Post "https://www.wenku8.net/login.php?do=submit&jumpurl=http%3A%2F%2Fwww.wenku8.net%2Findex.php": read tcp 192.168.1.2:61039->172.67.171.23:443: wsarecv: An existing connection was forcibly closed by the remote host.
未登录-(查询/热门小说)功能将无法使用

改成ipv4依旧无法使用:(

**Comment by AosakiReiya** [comment]
使用了代理吗？
能否访问https://www.wenku8.net？

文库官网有公告 (不知道是否有影响)：
     请中国移动网络用户注意：因文库网站域名（www.wenku8.net）被中移动的网络屏蔽，目前大部分地区无法访问，请中移动用户使用（www.wenku8.cc）访问网站，请大家帮忙广而告之，通知你认识的移动用户。
    其他网络的用户不受影响！不需要变更访问域名。

试试下面这个，换了个域名的版本
[Archive.zip](https://github.com/SamsonMXVI/go-wenku-downloader/files/13533429/Archive.zip)

**Comment by PantsuMeow** [comment]
我可以访问网页。（我也更换了移动的网络，没有被ban）
新的zip可以正常运行，感谢大佬帮助。:)
