### ISSUE TITLE
下载完成但无法生成epub,scraper.log报错如下

### ISSUE THREAD

**Issue by 1oath** [SamsonMXVI/go-wenku-downloader#6]
download.go:75: create epub failed: Error creating EPUB at "2259/***************.epub": open 2259/******************************************************.epub: The filename, directory name, or volume label syntax is incorrect.

怀疑是不是字符超了

**Comment by AosakiReiya** [comment]
应该是epub命名问题，试试看2.2.9的

**Comment by 1oath** [comment]
> 应该是epub命名问题，试试看2.2.9的

已成功下载生成，谢谢老哥，劳烦了
